export const GUEST_SERVICE_FEE_PERCENTAGE = Number(
  process.env.EXPO_PUBLIC_GUEST_SERVICE_FEE_PERCENTAGE!
);

export const HOST_SERVICE_FEE_PERCENTAGE = Number(
  process.env.EXPO_PUBLIC_HOST_SERVICE_FEE_PERCENTAGE!
);
